apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: hello-pipeline
spec:
  params:
    - name: message

  tasks:
    - name: hello
      taskRef: 
        name: echo
      params:
        - name: message
          value: $(params.message)
    # - name: hello2
    #   taskRef: 
    #     name: hello-world
    # - name: hello3
    #   taskRef: 
    #     name: hello-world

---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  params:
    - name: branch
      default: "main"
    - name: url

  tasks:
    - name: git-clone
      taskRef: 
        name: checkout
      params:
        - name: url
          value: $(params.url)
        - name: branch
          value: $(params.branch)